// landing/src/routes/docs/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte'
	import DocViewer from './DocViewer.svelte'

	// List of available documentation files
	const docs = [
		{ name: 'Install', url: '/vibe/docs/install.md' },
		{ name: 'Models', url: '/vibe/docs/models.md' },
		{ name: 'Debug', url: '/vibe/docs/debug.md' },
		{ name: 'Build', url: '/vibe/docs/building.md' },
	]

	// Set default selected document based on hash or default to the first doc
	let url: string
	onMount(() => {
		url = window.location.hash ? getDocUrl(window.location.hash) : docs[0].url
		// Watch for hash changes
		window.addEventListener('hashchange', () => {
			url = getDocUrl(window.location.hash)
		})
	})

	// Helper function to get the corresponding URL for a hash
	function getDocUrl(hash: string) {
		const docName = hash.replace('#', '') // Remove '#' from the hash
		const doc = docs.find((d) => d.name.toLowerCase() === docName.toLowerCase())
		return doc ? doc.url : docs[0].url // Default to the first doc if not found
	}
</script>

<div class="max-w-[81%] lg:max-w-[680px] m-auto" dir="ltr">
	<h1 class="text-4xl font-bold mb-6">Vibe Documentation</h1>

	<!-- Navigation -->
	<div class="mb-8 flex flex-wrap justify-center gap-2 rounded-xl border border-border bg-card/60 p-2">
		{#each docs as doc}
			<button
				class={`v-btn v-btn-sm ${url === doc.url ? 'v-btn-primary' : 'v-btn-ghost'}`}
				on:click={() => {
					url = doc.url
					window.location.hash = doc.name.toLowerCase() // Update hash
				}}>
				{doc.name}
			</button>
		{/each}
	</div>

	<!-- Content Area -->
	<div>
		<DocViewer {url} />
	</div>
</div>

// website/src/pages/Docs.tsx
import { useEffect, useState } from 'react'
import DocViewer from '~/components/DocViewer'
import { Button } from '~/components/ui/button'

const docs = [
  { name: 'Install', url: '/vibe/docs/install.md' },
  { name: 'Models', url: '/vibe/docs/models.md' },
  { name: 'Debug', url: '/vibe/docs/debug.md' },
  { name: 'Build', url: '/vibe/docs/building.md' },
]

function getDocUrl(hash: string) {
  const docName = hash.replace('#', '')
  const doc = docs.find((entry) => entry.name.toLowerCase() === docName.toLowerCase())

  return doc ? doc.url : docs[0].url
}

export default function Docs() {
  const [url, setUrl] = useState(docs[0].url)

  useEffect(() => {
    if (window.location.hash) {
      setUrl(getDocUrl(window.location.hash))
    }

    const onHashChange = () => setUrl(getDocUrl(window.location.hash))
    window.addEventListener('hashchange', onHashChange)

    return () => window.removeEventListener('hashchange', onHashChange)
  }, [])

  return (
    <div className="m-auto max-w-[81%] lg:max-w-[680px]" dir="ltr">
      <h1 className="mb-6 text-4xl font-bold">Vibe Documentation</h1>

      <div className="mb-8 flex flex-wrap justify-center gap-2 rounded-xl border border-border bg-card/60 p-2">
        {docs.map((doc) => (
          <Button
            key={doc.name}
            variant={url === doc.url ? 'default' : 'ghost'}
            size="sm"
            onClick={() => {
              setUrl(doc.url)
              window.location.hash = doc.name.toLowerCase()
            }}
          >
            {doc.name}
          </Button>
        ))}
      </div>

      <DocViewer url={url} />
    </div>
  )
}
