// website/src/pages/Features.tsx
import FeatureCard from '~/components/FeatureCard'
import features from '~/lib/features.json'

export default function Features() {
	return (
		<div className="m-auto max-w-[81%] lg:max-w-[680px]" dir="ltr">
			<div className="text-4xl font-bold">Features</div>
			<div className="mt-14 flex flex-col gap-28">
				{features.map((feature) => (
					<FeatureCard key={feature.title} {...feature} />
				))}
			</div>
		</div>
	)
}

// landing/src/routes/features/+page.svelte
<script>
	import { base } from '$app/paths'
	import features from '~/lib/features.json'
	import Feature from './feature.svelte'
</script>

<div class="max-w-[78%] lg:max-w-[600px] m-auto" dir="ltr">
	<div class="text-4xl font-bold">Features</div>

	<div class="flex flex-col gap-32 mt-14">
		{#each features as feature}
			<Feature {...feature} />
		{/each}
	</div>
</div>
