// landing/src/components/PostDownload.svelte
<script>
	import Heart from '~/icons/Heart.svelte'

	import { i18n } from '$lib/i18n'
	import { base } from '$app/paths'
	import SupportButton from './SupportButton.svelte'

	const t = $i18n.t
</script>

<dialog id="post-download-modal" class="v-dialog w-[92vw] max-w-md p-0">
	<div class="relative mx-auto p-6">
		<form method="dialog">
			<button class="v-btn v-btn-ghost v-btn-icon absolute right-2 top-2">✕</button>
		</form>
		<h3 class="text-xl font-semibold text-center">{t('your-download-is-starting')}</h3>
		<p class="py-2 text-sm text-center text-muted-foreground">{t('download-starting-description')}</p>
		<p class="text-center text-sm mt-5">{t('support-while-you-wait')}</p>
		<div class="flex justify-center mt-4">
			<SupportButton />
		</div>
	</div>
</dialog>

// website/src/components/PostDownload.tsx
import { useTranslation } from 'react-i18next'
import { Dialog, DialogContent } from '~/components/ui/dialog'
import SupportButton from './SupportButton'

interface PostDownloadProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  onOpenKofi: () => void
}

export default function PostDownload({ open, onOpenChange, onOpenKofi }: PostDownloadProps) {
  const { t } = useTranslation()

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="w-[92vw] max-w-md p-6">
        <h3 className="text-center text-xl font-semibold">{t('your-download-is-starting')}</h3>
        <p className="py-2 text-center text-sm text-muted-foreground">{t('download-starting-description')}</p>
        <p className="mt-5 text-center text-sm">{t('support-while-you-wait')}</p>
        <div className="mt-4 flex justify-center">
          <SupportButton onOpenKofi={onOpenKofi} />
        </div>
      </DialogContent>
    </Dialog>
  )
}
